import cardCover from "../../assets/universities/cardCover-min.jpeg";
import logo from "../../assets/universities/logo.svg";

export const Courses = [
  {
    title_full:"MBA (Master of Business Administration)",
    title: "MBA",
    duration: "2 years",
    description: "A postgraduate program focused on business and management, offering specializations in various domains.",
    specs: [
      "Marketing",
      "Finance",
      "Human Resource Management",
      "Business Analytics",
      "Operations Management",
      "International Business",
      "Healthcare Management",
      "IT Management",
      "Supply Chain Management",
      "Entrepreneurship",
      "Retail Management",
      "Banking & Financial Services",
      "Digital Marketing",
    ],
  },
  {
    title_full:"MCom (Master of Commerce)",
    title: "MCom",
    duration: "2 years",
    description: "A master's degree in commerce, covering finance, accounting, taxation, and business law.",
    specs: [
      "Corporate Accounting",
      "Financial Markets & Institutions",
      "Cost & Management Accounting",
      "Taxation",
      "Auditing",
      "Business Law",
      "Investment Management",
      "E-commerce & Digital Business",
      "Risk Management",
      "International Finance",
      "Banking & Insurance",
      "Accounting for Decision Making",
      "Corporate Governance & Ethics",
    ],
  },
  {
    title_full:"MCA (Master of Computer Applications)",
    title: "MCA",
    duration: "3 years",
    description: "A master's degree in computer applications, equipping students with advanced IT and software skills.",
    specs: [
      "Software Development",
      "Data Structures & Algorithms",
      "Database Management Systems",
      "Artificial Intelligence & Machine Learning",
      "Cloud Computing",
      "Cybersecurity & Ethical Hacking",
      "Mobile App Development",
      "Internet of Things (IoT)",
      "Blockchain Technology",
      "Computer Networks",
      "Full Stack Development",
      "Big Data Analytics",
      "Web Technologies",
    ],
  },
  {
    title_full:"MA (Master of Arts)",
    title: "MA",
    duration: "2 years",
    description: "A postgraduate degree focusing on humanities and social sciences, with specializations in various disciplines.",
    specs: [
      "English Literature",
      "Political Science",
      "Sociology",
      "Psychology",
      "Philosophy",
      "Public Administration",
      "History",
      "Economics",
      "Journalism & Mass Communication",
      "Anthropology",
      "Linguistics",
      "International Relations",
      "Development Studies",
    ],
  },
];


export const cardData = [
  {
    title: "Sikkim Manipal University",
    cover: cardCover,
    logo: logo,
    affiliation: "UGC, AICTE, EXAMPLE, EXAMPLE, EXAMPLE....",
    status: "Admission ongoing",
    review: "4/5",
  },
  {
    title: "Amity University",
    cover: cardCover,
    logo: logo,
    affiliation: "UGC, AICTE, NAAC, EXAMPLE, EXAM...",
    status: "Admissions Open",
    review: "3.8/5",
  },

  {
    title: "Manipal University Jaipur",
    cover: cardCover,
    logo: logo,
    affiliation: "UGC, AICTE, EXAMPLE, NAAC, EXAM...",
    status: "Admissions Open",
    review: "3.9/5",
  },
  {
    title: "Chandigarh University",
    cover: cardCover,
    logo: logo,
    affiliation: "UGC, AICTE, NAAC A+, EXAMPLE...",
    status: "Apply Now",
    review: "4.1/5",
  },
  {
    title: "SRM University",
    cover: cardCover,
    logo: logo,
    affiliation: "UGC, AICTE, NAAC, NIRF, EXAM...",
    status: "Few Seats Left",
    review: "4.3/5",
  },
  {
    title: "Jain University",
    cover: cardCover,
    logo: logo,
    affiliation: "UGC, AICTE, NAAC A+, EXAM...",
    status: "Admissions Open",
    review: "3.7/5",
  },
];
